### ISSUE TITLE
Design and create CMC class diagrams

### ISSUE THREAD

**Issue by NancyT0** [aishaxsyed/ISDM-Tut-7-Group-6#6]

**Comment by aishaxsyed** [comment]
![Class Diagram ISDM](https://user-images.githubusercontent.com/62279254/83324877-6f61a900-a2ab-11ea-8a22-9e56d407a74f.png)


Uploading Class Diagram for CMC

**Comment by aishaxsyed** [comment]
Class Diagram Completed
