### ISSUE TITLE
Design and create CMC collaborative diagrams

### ISSUE THREAD

**Issue by NancyT0** [aishaxsyed/ISDM-Tut-7-Group-6#7]

**Comment by aishaxsyed** [comment]
![Collaboration ISDM](https://user-images.githubusercontent.com/62279254/83324927-c2d3f700-a2ab-11ea-8e88-ae2d9262ee62.png)

Uploading Collaborative Diagram

**Comment by aishaxsyed** [comment]
Collaborative Diagram is complete
